Repository miaucl/bring-api, pull requests merged in 2024-02, with the labels that each got.

#8 Add test workflow
  .github/workflows/test.yaml
  .gitignore
  .vscode/tasks.json
  CHANGELOG.md
  README.md
  requirements_dev.txt
  setup.cfg
  test.py
Labels: good first issue

#14 revert change of notify method
  bring_api/bring.py
  test.py
Labels: question

#16 create const.py with constants for url and header
  bring_api/bring.py
  bring_api/const.py
Labels: small-pr

#10 Add localization support for catalog items
  .gitignore
  CHANGELOG.md
  bring_api/bring.py
  bring_api/const.py
  bring_api/exceptions.py
  bring_api/types.py
  setup.cfg
  test.py
Labels: enhancement

#19 update docstring
  bring_api/bring.py
Labels: small-pr

#21 Add locales from APK to package
  .gitignore
  CHANGELOG.md
  bring_api/bring.py
  bring_api/locales/articles.de-AT.json
  bring_api/locales/articles.de-CH.json
  bring_api/locales/articles.de-DE.json
  bring_api/locales/articles.en-AU.json
  bring_api/locales/articles.en-CA.json
  bring_api/locales/articles.en-GB.json
  bring_api/locales/articles.en-US.json
  bring_api/locales/articles.es-ES.json
  bring_api/locales/articles.fr-CH.json
  bring_api/locales/articles.fr-FR.json
  bring_api/locales/articles.hu-HU.json
  bring_api/locales/articles.it-CH.json
  bring_api/locales/articles.it-IT.json
  bring_api/locales/articles.nb-NO.json
  bring_api/locales/articles.nl-NL.json
  bring_api/locales/articles.pl-PL.json
  bring_api/locales/articles.pt-BR.json
  bring_api/locales/articles.ru-RU.json
  bring_api/locales/articles.sv-SE.json
  bring_api/locales/articles.tr-TR.json
  prepare_locales_catalog.py
  setup.cfg
  test.py
Labels: bug
